apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: healthapi-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: healthapi
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 20
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
      selectPolicy: Min
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
