apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthapi
  annotations:
    description: "Deployment para a API cadastro"
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
      labels:
        app: label-healthapi
    spec:
      containers:
      - name: cont-healthapi
        image: healthapiapiv1:latest
        imagePullPolicy: Never
        envFrom:
            - secretRef:
                name: database-secrets
            - secretRef:
                name: rabbitmq-secrets
            - configMapRef:
                name: config-rabbitmq
            - configMapRef:
                name: config-database
        env:
            - name: ASPNETCORE_URLS
              value: http://*:8080
        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "256Mi"
        ports:
        - containerPort: 8080
  selector:
    matchLabels:
      app: label-healthapi
