@HealthMedApplication_HostAddress = http://localhost:5067

GET {{HealthMedApplication_HostAddress}}/todos/
Accept: application/json

###

GET {{HealthMedApplication_HostAddress}}/todos/1
Accept: application/json

###
