apiVersion: v1
kind: Service
metadata:
  name: svc-healthworker
  annotations:
    description: "Servico para expor o WORKER de cadastro dentro do cluster para os demais pods"
spec:
  type: NodePort
  selector:
    app: label-healthworker
  ports:
  - port: 8084
    nodePort: 30022
    
    
