apiVersion: v1
kind: Service
metadata:
  name: svc-scheduleapi
  annotations:
    description: "Servico para expor a API de agendamento para fora do cluster"
spec:
  type: NodePort
  selector:
    app: label-scheduleapi
  ports:
  - port: 8081
    nodePort: 30021
    
