apiVersion: v1
kind: Service
metadata:
  name: svc-healthapi
  annotations:
    description: "Servico para expor a API de cadastro para fora do cluster"
spec:
  type: NodePort
  selector:
    app: label-healthapi
  ports:
  - port: 8085
    nodePort: 30020
    
