apiVersion: v1
kind: Service
metadata:
  name: svc-scheduleworker
  annotations:
    description: "Servico para expor o WORKER de agendamento dentro do cluster para os demais pods"
spec:
  type: NodePort
  selector:
    app: label-scheduleworker
  ports:
  - port: 8083
    nodePort: 30023
    
    
