name: HealthMed

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dotnet_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Cache .NET packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/packages.config') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.300
  
      - name: Restore dependencies
        run: dotnet restore HealthMed
  
      - name: Build
        run: dotnet build HealthMed --no-restore
        
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
     
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
         dotnet-version: 8.0.300
         
      - name: Restore Dependencies
        run: cd HealthMed && dotnet restore
        
      - name: Build
        run: cd HealthMed && dotnet build --no-restore
  
      - name: Docker Build - HealthMedAPI
        working-directory: ./HealthMed
        run: docker build -t healthmedapiv1 -f "1 - APIs/HealthMedApi/Dockerfile" .
      - name: Docker Build - ScheduleAPI
        working-directory: ./HealthMed
        run: docker build -t scheduleapiv1 -f "1 - APIs/ScheduleApi/Dockerfile" .
      
