name: HealthMed

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
     
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
         dotnet-version: 8.0.300
         
      - name: Restore Dependencies
        run: cd Contact && dotnet restore
        
      - name: Build
        run: cd Contact && dotnet build --no-restore
  
      - name: HealthMedAPI - Build the Docker image
        run: docker build --no-cache -t healthmedapiv1 -f "1 - APIs/HealthMedAPI/Dockerfile" .
      - name: ScheduleAPI - Build the Docker image
        run: docker build --no-cache -t scheduleapiv1 -f "1 - APIs/ScheduleAPI/Dockerfile" .
      
