name: HealthMed

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: HealthMedAPI - Build the Docker image
      run: docker build --no-cache -t healthmedapiv1 -f "1 - APIs/HealthMedAPI/Dockerfile" .
    - name: ScheduleAPI - Build the Docker image
      run: docker build --no-cache -t scheduleapiv1 -f "1 - APIs/ScheduleAPI/Dockerfile" .
      
