name: HealthMed

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
     
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
         dotnet-version: 8.0.300
         
      - name: Restore Dependencies
        run: cd HealthMed && dotnet restore
        
      - name: Build
        run: cd HealthMed && dotnet build --no-restore
  
      - name: Docker Build - HealthMedAPI
        run: docker build -t healthmedapiv1 -f "HealthMed/1 - APIs/HealthMedApi/Dockerfile" .
      #   run: docker build --no-cache -t healthmedapiv1 -f "HealthMed/1 - APIs/HealthMedAPI/Dockerfile" .
      # - name: Docker Build - ScheduleAPI
      #   run: docker build -t scheduleapiv1 -f 'HealthMed/1 - APIs/ScheduleAPI/Dockerfile' .
      
